export const getProductBackgroundColor = (item: string) => {
    const colorMap: { [key: string]: string } = {
        'tomato': '#ffebee',
        'potato': '#f3e5ab',
        'carrot': '#ffecce',
        'banana': '#fff9c4',
        'apple': '#ffebee',
        'orange': '#fff3e0',
        'mango': '#fff9c4',
        'pineapple': '#fff9c4',
        'papaya': '#fff3e0',
        'guava': '#f1f8e9',
        'lychee': '#fce4ec',
        'coconut': '#f5f5f5',
        'lemon': '#fffde7',
        'lime': '#f1f8e9',
        'watermelon': '#ffebee',
        'melon': '#f1f8e9',
        'grapes': '#f3e5f5',
        'strawberry': '#ffebee',
        'onion': '#f5f5f5',
        'cabbage': '#f1f8e9',
        'lettuce': '#f1f8e9',
        'spinach': '#e8f5e8',
        'broccoli': '#e8f5e8',
        'cauliflower': '#f5f5f5',
        'bell_pepper': '#f1f8e9',
        'chili': '#ffebee',
        'cucumber': '#e8f5e8',
        'eggplant': '#f3e5f5',
        'okra': '#e8f5e8',
        'green_beans': '#e8f5e8',
        'pumpkin': '#fff3e0',
        'beetroot': '#fce4ec',
        'radish': '#ffebee',
        'ginger': '#fff3e0',
        'garlic': '#f5f5f5'
    };
    return colorMap[item] || '#f5f5f5';
};
